# 2.int与str的相互转换
print("众所周知，input()方法中用户输入的值默认为str，例如：")
a = input("请输入一个两位数字：")
print("你输入的两位数字为：")
print(a)
print("虽然你输入的是纯数字，但它的数据类型仍然为：")
print(type(a))
print("使用int()方法可以将str类型的数据转换为int类型。运行代码b = int(a)后，b的值和数据类型为：")
b = int(a)
print(b)
print(type(b))
print("使用str()方法又可以将int类型的数据转换为str类型。运行代码c = str(b)后，c的值和数据类型为：")
c = str(b)
print(c)
print(type(c))